server:
  port: 8080
  servlet:
    context-path: /api/theater-mgnt

spring:
  application:
    name: theater-mgnt

  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.zpjvpfkwbcnszfzdwynf
    password: 3kSE347@123

    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
        order_inserts: true
  ai:
    openai:
      api-key: ${GEMINI_KEY}
      base-url: https://generativelanguage.googleapis.com

      chat:
        completions-path: v1beta/openai/chat/completions
        options:
          model: gemini-2.5-flash
      embedding:
        embeddings-path: v1beta/openai/embeddings
        options:
          model: text-embedding-004
    vectorstore:
      pgvector:
        dimension: 768
        index-type: HNSW
        initialize-schema: true
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

outbound:
  identity:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: "http://localhost:3000/authenticate"

jwt:
  signerKey: "+PAV/uNVIsN2N1peTkAViUZSSc+t8/wOZQDw8M2+HxBD/2dFy9segSiMPHBr+q97"
  refreshable-duration: 36000
  valid-duration: 3600
otp:
  valid-duration: 10

brevo:
  apiKey: ${BREVO_API_KEY}
vnpay:
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:3000/payment/vnpay-return
  ipn-url: http://localhost:8080/api/theater-mgnt/payment/vnpay-ipn
  version: 2.1.0
  command: pay
  order-type: other

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

# Socket.IO Configuration for real-time communication
socketio:
  port: 9092

logging:
  level:
    com.theatermgnt.theatermgnt.chatbotInternal.util.DocumentSectionTracker: DEBUG
